---
title: "Country assortativity and MF TB incidence"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}

library(tidyverse)

ilo <- readxl::read_excel("ILO-employment.xlsx", skip=5)

country.ilo <- ilo %>% filter(Age=="15+", Time==2016) %>%
  group_by(`Reference area`) %>%
  summarise(male=mean(Male), female=mean(Female)) %>% mutate(work_ratio=male/female) %>%
  rename(country=`Reference area`)

who <- read_csv("TB_burden_countries_2018-06-12.csv")

country.who <- who %>% filter(year==2016) %>% group_by(country) %>% 
  summarise(inc=mean(e_inc_100k), mf_inc=(e_inc_num_m/e_inc_num_f), pop_size=e_pop_num, region=g_whoregion)

```

```{r countryMFRatio, fig.cap="Estimated total incidence against estimated male to female incidence in WHO countries (2016). "}

country.who %>% 
  ggplot(aes(inc, mf_inc, color=region, size=pop_size)) + geom_point() +
  geom_hline(yintercept = 1, linetype="dotted", 
                color = "black", size=.5) + 
  xlab("Estimated incidence (per 100,000)") + ylab("Estimated male:female incidence")



```


```{r}

ilo.who <- full_join(country.ilo, country.who, by="country")

```

```{r}

ilo.who %>% 
  filter(!is.na(region)) %>%
  ggplot(aes(work_ratio, mf_inc, color=region, size=inc)) + geom_point() +
  geom_hline(yintercept = 1, linetype="dotted", 
                color = "black", size=.5) + 
  xlab("Estimated male:female employment ratio") + 
  ylab("Estimated male:female incidence") + 
  facet_wrap(~region, scales = "free") + geom_smooth(method="lm")

```

