---
title: "Network sensitivity analysis for TB-assortativity"
output: pdf_document
editor_options: 
  chunk_output_type: console
header-includes: 
- \usepackage[section]{placeins}
- \usepackage{amsmath}
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(readr)
library(magrittr)
library(tidyr)
library(igraph)
library(ggplot2)
library(cowplot)
library(plotrix)
library(knitr)
library(colorspace)
library(tidyverse)
library(gridExtra)
library(ggraph)

knitr::opts_chunk$set(cache=TRUE, fig.path = "slirs-par-figs/", 
                      warning = FALSE, message=FALSE, echo=FALSE, fig.height =6, fig.width = 8) 

# colors for assortativity
assortCols <- c("#F3E79AFF", "#F7A086FF", "#CF63A6FF", "#704D9EFF")

```


# How does assorted network generation affect results? 

* Preliminary results for 50 replicates on networks generated with Sah algorithm (r=0, .3, .6, .9)
* One epidemic simulated per network


```{r}

res <- read.csv("simulations-sah/res_sah_50.csv")

res$modNameLatent <- ifelse(res$reactivation_rate==0.1, T, F)
res$modNameRecover <- ifelse(res$reversion_rate==0.33, T, F)
res$modName <- NA
res$modName[!res$modNameLatent&!res$modNameRecover] <- "SIR"
res$modName[res$modNameLatent&!res$modNameRecover] <- "SLIR"
res$modName[!res$modNameLatent&res$modNameRecover] <- "SIRS"
res$modName[res$modNameLatent&res$modNameRecover] <- "SLIRS"

res$alph_type <- factor(res$alph_type, labels = c("IP", "SUS", "TRA"))

res$mf_r_ratio <- res$m_rec/res$f_rec
res$mf_i_ratio <- res$m_inf/res$f_inf

res$r <- res$r * 2 # sah uses modularity, so assortaaivity is multipled by 2

```


```{r prev-rat-heatmap-low-tau, fig.cap="The effects of sex-traits and assortativity on male-bias in simulations on Sah-networks.", fig.height=8}

hs <- 14 # text size
 
res %>%
  filter(!is.infinite(mf_r_ratio), tau==0.075, modName%in%c("SLIR", "SIR")) %>%
  group_by(modName, net_type, alph_type, r, alph_val) %>%
  summarise(meanPrev=mean(mf_r_ratio, na.rm=TRUE)) -> fooa

res %>%
  filter(!is.infinite(mf_i_ratio), tau==0.075, modName%in%c("SLIRS", "SIRS")) %>%
  group_by(modName, net_type, alph_type, r, alph_val) %>%
  summarise(meanPrev=mean(mf_i_ratio, na.rm=TRUE)) -> foob

# for SLIR use R, for SLIRS use I class for MF calculation
foo <- bind_rows(fooa, foob)

foo %>%
  mutate(absPrev=abs(meanPrev-1.8)) %>%
  group_by(net_type, modName, alph_type, r) %>%
  summarise(alphVal=which.min(absPrev)) -> foo2

foo %>%
  ggplot(aes(x=factor(r), y=factor(alph_val))) +
  geom_tile(aes(fill=meanPrev)) + 
  scale_fill_gradient2(midpoint=log10(1.8), trans="log10", 
                                     low="red4", mid = "dodgerblue",
                       high="black", limits=c(1.25,max(foo$meanPrev)), na.value = "white") +
  # geom_point(data=foo2, aes(x=factor(r), y=alphVal), 
  #            shape=17, color="white") +
  facet_grid(modName ~ alph_type) +
  labs(x="Assortativity (r)", y=expression(alpha), 
       fill="Mean \nPrevalence \nRatio", title = "R0=1.5") +
  theme_bw() +
  theme(axis.text=element_text(size=hs),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=hs,face="bold"),
        legend.title = element_text(size=hs),
        legend.text = element_text(size=hs), 
        # panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 18, color="Black")) 

```

\clearpage

```{r outbreak-compare1, fig.cap=""}

foo <- res %>% 
  filter(modName%in% c("SIR", "SLIR"), alph_val==1) %>%
  mutate(out_size=(m_rec + f_rec)/1000) %>%
  group_by(modName, tau, r) %>%
  summarise(out_size=mean(out_size))

foo %>%
  filter(modName=="SLIR") %>%
  ggplot(aes(x=as.factor(r), y=factor(tau))) +
  geom_tile(aes(fill=out_size)) + 
  scale_fill_viridis_c() +
  facet_grid(. ~ modName) +
  labs(x="Assortativity (r)", y=expression(tau), 
       fill="Epidemic \n size") +
  theme_bw() +
  theme(axis.text=element_text(size=14),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title.y = element_text(angle=0, vjust = 0.5),
        axis.title=element_text(size=14,face="bold"),
        legend.title = element_text(size=14),
        legend.text = element_text(size=14), 
        # panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 14, color="Black")) 


res %>%
  filter(modName=="SLIR", tau %in% c(0.04, 0.15)) %>%
  mutate(size=(f_rec + m_rec)) %>%
  ggplot(aes(x=factor(r), y=size)) +
  geom_boxplot()  +  facet_wrap(tau~.) +
  #scale_color_continuous_diverging() +
  labs(x="Assortativity (r)", y=("Epidemic size"), 
       fill="Network \n type", shape="Model \n type") +
  theme_bw() +
  theme(axis.text=element_text(size=14),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=14,face="bold"),
        legend.title = element_text(size=14),
        legend.text = element_text(size=14), 
        # panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 14, color="Black")) 

```


```{r outbreak-compare2, fig.cap="Effects of assortativity on endemic prevalence in SLIRS model (top row) and epidemic size in SLIR model (bottom row). Columns show results for models with different transmission rates. ", fig.width=8, fig.height=7}

foo <- res %>% 
  filter(modName%in% c("SIRS", "SLIRS"), alph_val==1) %>%
  mutate(infected_prev=(m_inf+f_inf)/1000) %>%
  group_by(modName, tau, r) %>%
  summarise(prev=mean(infected_prev))

foo %>%
  filter(modName=="SLIRS") %>%
  ggplot(aes(x=as.factor(r), y=factor(tau))) +
  geom_tile(aes(fill=prev)) + 
  scale_fill_viridis_c() +
  facet_grid(. ~ modName) +
  labs(x="Assortativity (r)", y=expression(tau), 
       fill="Endemic \n prevalence") +
  theme_bw() +
  theme(axis.text=element_text(size=14),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title.y = element_text(vjust=.5, angle=0),
        axis.title=element_text(size=14,face="bold"),
        legend.title = element_text(size=14),
        legend.text = element_text(size=14), 
        # panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 14, color="Black")) -> endemicHeat

res %>%
  filter(modName=="SLIRS", tau %in% c(0.04, 0.15)) %>%
  mutate(infected_prev=(m_inf+f_inf)/1000) %>%
  ggplot(aes(x=factor(r), y=infected_prev)) +
  geom_boxplot()  +  facet_wrap(tau~.) + ggtitle("SLIRS") +
  #scale_color_continuous_diverging() +
  labs(x="Assortativity (r)", y=("Endemic prevalence"), 
       fill="Network \n type", shape="Model \n type") +
  theme_bw() +
  theme(axis.text=element_text(size=14),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=14,face="bold"),
        legend.title = element_text(size=14),
        legend.text = element_text(size=14), 
        # panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 14, color="Black")) -> endemicBox

foo2 <- res %>% 
  filter(modName%in% c("SLIR"), alph_val==1) %>%
  mutate(prev=(m_rec+f_rec)/1000) %>%
  group_by(modName, tau, r) %>%
  summarise(recovered_prev=mean(prev))


foo2 %>%
  filter(modName=="SLIR", tau %in% c(0.04, 0.15)) %>%
  ggplot(aes(x=factor(r), y=recovered_prev)) +
  geom_boxplot()  +  facet_wrap(tau~.) + ggtitle("SLIR") +
  #scale_color_continuous_diverging() +
  labs(x="Assortativity (r)", y=("Epidemic size"), 
       fill="Network \n type", shape="Model \n type") +
  theme_bw() +
  theme(axis.text=element_text(size=14),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=14,face="bold"),
        legend.title = element_text(size=14),
        legend.text = element_text(size=14), 
        # panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 14, color="Black")) -> epidemicBox



grid.arrange(endemicBox, epidemicBox)

```

\clearpage

## Sensitivity analyses (Supplements)

```{r}

res %>%
  gather("stat", "val", c(net_clustering, net_path_len, net_deg_assort)) %>%
  ggplot(aes(factor(r), val)) + geom_boxplot() + facet_grid(stat~., scales="free")
  


```


```{r}

res %>% 
  gather("stat", "val", c(net_clustering, net_path_len, net_deg_assort)) %>%
  ggplot(aes(val, mf_i_ratio, color=factor(alph_val))) + 
  geom_smooth() +
  facet_grid(alph_type~stat, scales="free_x") +
  theme_bw() +
  theme(axis.text=element_text(size=14),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=14,face="bold"),
        legend.title = element_text(size=14),
        legend.text = element_text(size=14), 
        # panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 14, color="Black")) 

res %>% 
  gather("stat", "val", c(net_clustering, net_path_len, net_deg_assort)) %>%
  ggplot(aes(val, mf_r_ratio, color=factor(alph_val))) + 
  geom_smooth() +
  facet_grid(alph_type~stat, scales="free_x") +
  theme_bw() +
  theme(axis.text=element_text(size=14),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=14,face="bold"),
        legend.title = element_text(size=14),
        legend.text = element_text(size=14), 
        # panel.grid.major = element_blank(),
        # panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 14, color="Black")) 


res %>% 
  select(net_clustering, net_deg_assort, net_path_len, r, mf_i_ratio, mf_r_ratio) %>%
  ggpairs(aes(color=factor(r))) 

```


