---
title: "Sex-assortativity, heterogeneity in infection and transmission by sex, and male-bias in TB cases: A simulation study"
output: pdf_document
editor_options: 
  chunk_output_type: console
header-includes: \usepackage[section]{placeins}
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(readr)
library(magrittr)
library(tidyr)
library(igraph)
library(ggplot2)
library(cowplot)
library(plotrix)
library(knitr)
library(colorspace)
library(tidyverse)
library(gridExtra)

knitr::opts_chunk$set(cache=TRUE, fig.path = "slirs-par-figs/", 
                      warning = FALSE, message=FALSE, echo=FALSE, fig.height =6, fig.width = 8) 

# colors for assortativity
assortCols <- c("#F3E79AFF", "#F7A086FF", "#CF63A6FF", "#704D9EFF")

```


```{r who-male-bias, fig.cap="Across the world, more cases of TB occur among men than women (A). These patterns are remarkably similar across regions and are not explained by rates of smoking (B), health coverage (C), or employment (D)."}

# data from 
# http://apps.who.int/gho/portal/uhc-cabinet-wrapper-v2.jsp?id=1010501

ilo <- readxl::read_excel("ILO-employment.xlsx", skip=5)

country.ilo <- ilo %>% filter(Age=="15+", Time==2016) %>%
  rename(male=`Male...6`, female=`Female...7`, country=`Reference area`) %>%
  select(male, female, country) %>%
  group_by(country) %>%
  summarise(male=mean(male), female=mean(female)) %>% 
  mutate(work_ratio=male/female)

who <- read_csv("TB_burden_countries_2018-06-12.csv")

health <- read_csv("data-health.csv", skip = 1) %>%
  rename(country=Country, UHC=`2017`) %>%
  select(country, UHC)

smoke <- read_csv("data-smoke.csv", skip = 1) %>%
  rename(country=Country) %>%
  select(country, Year, Male, Female) %>%
  filter(Year==2015) %>%
  mutate(Male=substr(Male, 1,4), Female=substr(Female, 1,4)) %>%
  mutate(Male=as.numeric(Male), Female=as.numeric(Female)) %>%
  mutate(mf_smoke=Male/Female)

country.who <- who %>% 
  filter(year==2016) %>% group_by(country) %>% 
  summarise(inc=mean(e_inc_100k),
            mf_inc=(e_inc_num_m/e_inc_num_f), 
            pop_size=e_pop_num, region=g_whoregion)

ilo.who <- full_join(country.ilo, country.who, by="country")
ilo.who <- full_join(ilo.who, health, by="country")
ilo.who <- full_join(ilo.who, smoke, by="country")

### plots

country.who %>% 
  ggplot(aes(mf_inc, fill=region)) +
  geom_histogram(bins = 20, show.legend=FALSE) +
  facet_wrap(.~region) +
  geom_vline(xintercept = 1, linetype="dotted", 
                color = "black", size=.5) + 
  labs(x="Estimated male:female incidence, 2016", y="", title="A") + 
  theme_light() -> mfplot

# country.who %>% 
#   ggplot(aes(inc, mf_inc, color=region)) +
#   geom_point(show.legend=FALSE) +
#   #scale_y_continuous(trans="log10") + 
#   geom_smooth(method="lm", se=FALSE, show.legend = FALSE,
#               size=.5) +
#   geom_hline(yintercept = 1, linetype="dotted", 
#                 color = "black", size=.5) + 
#   labs(x="Estimated incidence (per 100,000)", y="Estimated male:female incidence", title="B") +
#   theme_light()  -> incplot

ilo.who %>% 
  ggplot(aes(mf_smoke, mf_inc, color=region)) +
  geom_point(show.legend=FALSE) +
  scale_x_continuous(trans="log10") + 
  geom_smooth(method="lm", se=FALSE, show.legend = FALSE, 
              size=.5) +
  geom_hline(yintercept = 1, linetype="dotted", 
                color = "black", size=.5) + 
  labs(x="Estimated male:female smoking rates, 2015", 
       y="Estimated male:female incidence, 2016", title="B") +
  theme_light()  -> smokeplot

ilo.who %>% 
  ggplot(aes(UHC, mf_inc, color=region)) +
  geom_point(show.legend=FALSE) +
  #scale_y_continuous(trans="log10") + 
  geom_smooth(method="lm", se=FALSE, show.legend = FALSE, 
              size=.5) +
  geom_hline(yintercept = 1, linetype="dotted", 
                color = "black", size=.5) + 
  labs(x="Universal Health Coverage Index, 2017", y="Estimated male:female incidence, 2016", title="C") +
  theme_light()  -> healthplot

ilo.who %>% 
  filter(!is.na(region)) %>%
  ggplot(aes(work_ratio, mf_inc, color=region)) + 
  geom_point(show.legend = FALSE) +
  scale_x_continuous(trans="log10") + 
  geom_smooth(method="lm", se=FALSE, show.legend = FALSE, 
              size=.5) +
  geom_hline(yintercept = 1, linetype="dotted", 
                color = "black", size=.5) + 
  labs(x="Estimated male:female employment ratio, 2016", y="Estimated male:female incidence, 2016", title = "D") +
  #facet_wrap(~region) +
  theme_light() -> workplot

grid.arrange(
  mfplot, smokeplot, healthplot, workplot,
  widths = c(1, 1),
  layout_matrix = rbind(c(1, 2),
                        c(3, 4))
)

```

Take-aways for data exploration: 

* Male-bias similar across regions
* No strong predictors of male-bias at the country scale

\newpage

```{r}

res <- read.csv("simulations-rewiring/SLIRS-res/test3.csv")

# model comparison 
res$modNameLatent <- ifelse(res$reactivation_rate==0.1, T, F)
res$modNameRecover <- ifelse(res$reversion_rate==0.33, T, F)
res$modName <- NA
res$modName[!res$modNameLatent&!res$modNameRecover] <- "SIR"
res$modName[res$modNameLatent&!res$modNameRecover] <- "SLIR"
res$modName[!res$modNameLatent&res$modNameRecover] <- "SIRS"
res$modName[res$modNameLatent&res$modNameRecover] <- "SLIRS"

# network types
res$type_net <- factor(res$type_net, labels = c("Scale-free", "Small-world"))
res$alph_type <- factor(res$alph_type, labels = c("IP", "SUS", "TRA"))


```

```{r SLIR-prev-rat-low-tau, fig.cap="The effects of assortativity on male-bias in SLIR model.  Vertical panels show sex-trait ratios ($\\alpha$) for sex-traits shown at the bottom including male:female infectious period (IP), susceptibility (SUS), and transmissibility (TRA). Hortizontal panels show different network types (scale-free and small-world). The red dashed line shows the observed ratio of male:female cases globally and the grey dashed line represents even distribution of cases between men and women. Results for $\\tau=0.075$ shown. "}

 
res %>%
  filter(modName == "SLIR", tau == 0.075) %>%
  ggplot(aes(x=as.factor(alph_type), y=mf_r_ratio, fill=factor(r))) +
  geom_boxplot() + facet_grid(type_net ~ alph_val) +
  geom_hline(yintercept=1.8, linetype="dashed", 
                color = "red", size=.75) +    
  geom_hline(yintercept=1, linetype="dashed", 
                color = "grey", size=.5)   +
  scale_y_continuous(trans="log10", limits = c(.5, 10)) + 
  scale_fill_discrete_sequential(palette="Sunset") +
  labs(x="Sex trait", y="M:F case bias", 
       fill="Assortativity", title = "SLIR, R0=1.5") +
  theme_light() +
  theme(axis.text=element_text(size=14),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=18,face="bold"),
        legend.title = element_text(size=18),
        legend.text = element_text(size=18), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 18, color="Black"))

```


```{r SLIR-prev-rat-high-tau, fig.cap="The effects of assortativity on male-bias in SLIR model.  Vertical panels show sex-trait ratios ($\\alpha$) for sex-traits shown at the bottom including male:female infectious period (IP), susceptibility (SUS), and transmissibility (TRA). Hortizontal panels show different network types (scale-free and small-world). The red dashed line shows the observed ratio of male:female cases globally and the grey dashed line represents even distribution of cases between men and women. Results for $\\tau=0.15$ shown. "}

 
res %>%
  filter(modName == "SLIR", tau == 0.15) %>%
  ggplot(aes(x=as.factor(alph_type), y=mf_r_ratio, fill=factor(r))) +
  geom_boxplot() + facet_grid(type_net ~ alph_val) +
  geom_hline(yintercept=1.8, linetype="dashed", 
                color = "red", size=.75) +    
  geom_hline(yintercept=1, linetype="dashed", 
                color = "grey", size=.5)   +
  scale_y_continuous(trans="log10", limits = c(.25, 10)) + 
  scale_fill_discrete_sequential(palette="Sunset") +
  labs(x="Sex trait", y="M:F case bias", 
       fill="Assortativity", title = "SLIR, R0=3.5") +
  theme_light() +
  theme(axis.text=element_text(size=14),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=18,face="bold"),
        legend.title = element_text(size=18),
        legend.text = element_text(size=18), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 18, color="Black"))

```


```{r SLIRS-prev-rat-low-tau, fig.cap="The effects of assortativity on male-bias in SLIRS model.  Vertical panels show sex-trait ratios ($\\alpha$) for sex-traits shown at the bottom including male:female infectious period (IP), susceptibility (SUS), and transmissibility (TRA). Hortizontal panels show different network types (scale-free and small-world). The red dashed line shows the observed ratio of male:female cases globally and the grey dashed line represents even distribution of cases between men and women. Results for $\\tau=0.075$ shown. "}


res %>%
  filter(modName == "SLIRS", tau == 0.075) %>%
  ggplot(aes(x=as.factor(alph_type), y=mf_i_ratio, fill=factor(r))) +
  geom_boxplot() + facet_grid(type_net ~ alph_val) +
  geom_hline(yintercept=1.8, linetype="dashed", 
                color = "red", size=.75) +    
  geom_hline(yintercept=1, linetype="dashed", 
                color = "grey", size=.5)   +
  scale_y_continuous(trans="log10", limits = c(.25, 10)) + 
  scale_fill_discrete_sequential(palette="Sunset") +
  labs(x="Sex-trait", y="M:F case bias", 
       fill="Assortativity", title = "SLIRS, R0=1.5") +
  theme_light() +
  theme(axis.text=element_text(size=14),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=18,face="bold"),
        legend.title = element_text(size=18),
        legend.text = element_text(size=18), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 18, color="Black"))

```

```{r SLIRS-prev-rat-high-tau, fig.cap="The effects of assortativity on male-bias in SLIRS model.  Vertical panels show sex-trait ratios ($\\alpha$) for sex-traits shown at the bottom including male:female infectious period (IP), susceptibility (SUS), and transmissibility (TRA). Hortizontal panels show different network types (scale-free and small-world). The red dashed line shows the observed ratio of male:female cases globally and the grey dashed line represents even distribution of cases between men and women. Results for $\\tau=0.15$ shown. "}


res %>%
  filter(modName == "SLIRS", tau == 0.15) %>%
  ggplot(aes(x=as.factor(alph_type), y=mf_i_ratio, fill=factor(r))) +
  geom_boxplot() + facet_grid(type_net ~ alph_val) +
  geom_hline(yintercept=1.8, linetype="dashed", 
                color = "red", size=.75) +    
  geom_hline(yintercept=1, linetype="dashed", 
                color = "grey", size=.5)   +
  scale_y_continuous(trans="log10", limits = c(.25, 10)) + 
  scale_fill_discrete_sequential(palette="Sunset") +
  labs(x="Sex-trait", y="M:F case bias", 
       fill="Assortativity", title = "SLIRS, R0=3.5") +
  theme_light() +
  theme(axis.text=element_text(size=14),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=18,face="bold"),
        legend.title = element_text(size=18),
        legend.text = element_text(size=18), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 18, color="Black"))

```


```{r prev-rat-heatmap-low-tau, fig.cap="The combined effects of assortativity and individual-level variation on male-bias across different sex-traits and network types. Vertical panels show type of sex-traits: Infectious period (IP), Susceptibility (SUS), and Transmissibility (TRA). Horizontal panels show model types (SLIR and SLIRS) and network type (scale-free and small-world). Color shows mean value of male:female prevalence for that parameter combination (only values above 1.25 are shown). In general, higher male susceptibility can lead to some amount of male-bias, but for SLIRS models, longer male infectious periods is a striking driver of male-bias.   ", fig.height=8}

hs <- 14 # text size
 
res %>%
  filter(!is.infinite(mf_r_ratio), tau==0.075, modName==("SLIR")) %>%
  group_by(modName, type_net, alph_type, r, alph_val) %>%
  summarise(meanPrev=mean(mf_r_ratio, na.rm=TRUE)) -> fooa

res %>%
  filter(!is.infinite(mf_i_ratio), tau==0.075, modName==c("SLIRS")) %>%
  group_by(modName, type_net, alph_type, r, alph_val) %>%
  summarise(meanPrev=mean(mf_i_ratio, na.rm=TRUE)) -> foob

# for SLIR use R, for SLIRS use I class for MF calculation
foo <- bind_rows(fooa, foob)

foo %>%
  mutate(absPrev=abs(meanPrev-1.8)) %>%
  group_by(type_net, modName, alph_type, r) %>%
  summarise(alphVal=which.min(absPrev)) -> foo2

foo %>%
  ggplot(aes(x=factor(r), y=factor(alph_val))) +
  geom_tile(aes(fill=meanPrev)) + 
  scale_fill_gradient2(midpoint=log10(1.8), trans="log10", 
                                     low="red4", mid = "dodgerblue",
                       high="black", limits=c(1.25,5), na.value = "white") +
  # geom_point(data=foo2, aes(x=factor(r), y=alphVal), 
  #            shape=17, color="white") +
  facet_grid(type_net ~ modName ~ alph_type) +
  labs(x="Assortativity", y=expression(alpha), 
       fill="Mean \nPrevalence \nRatio", title = "R0=1.5") +
  theme_light() +
  theme(axis.text=element_text(size=hs),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=hs,face="bold"),
        legend.title = element_text(size=hs),
        legend.text = element_text(size=hs), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 18, color="Black")) 

```

```{r prev-rat-heatmap-high-tau, fig.cap="The combined effects of assortativity and individual-level variation on male-bias across different sex-traits and network types. Vertical panels show type of sex-traits: Infectious period (IP), Susceptibility (SUS), and Transmissibility (TRA). Horizontal panels show model types (SLIR and SLIRS) and network type (scale-free and small-world). Color shows mean value of male:female prevalence for that parameter combination (only values above 1.25 are shown). In general, higher male susceptibility can lead to some amount of male-bias, but for SLIRS models, longer male infectious periods is a striking driver of male-bias.   ", fig.height=8}

hs <- 14 # text size
 
res %>%
  filter(!is.infinite(mf_r_ratio), tau==0.15, modName==("SLIR")) %>%
  group_by(modName, type_net, alph_type, r, alph_val) %>%
  summarise(meanPrev=mean(mf_r_ratio, na.rm=TRUE)) -> fooa

res %>%
  filter(!is.infinite(mf_i_ratio), tau==0.15, modName==c("SLIRS")) %>%
  group_by(modName, type_net, alph_type, r, alph_val) %>%
  summarise(meanPrev=mean(mf_i_ratio, na.rm=TRUE)) -> foob

# for SLIR use R, for SLIRS use I class for MF calculation
foo <- bind_rows(fooa, foob)

foo %>%
  mutate(absPrev=abs(meanPrev-1.8)) %>%
  group_by(type_net, modName, alph_type, r) %>%
  summarise(alphVal=which.min(absPrev)) -> foo2

foo %>%
  ggplot(aes(x=factor(r), y=factor(alph_val))) +
  geom_tile(aes(fill=meanPrev)) + 
  scale_fill_gradient2(midpoint=log10(1.8), trans="log10", 
                                     low="red4", mid = "dodgerblue",
                       high="black", limits=c(1.25,5), na.value = "white") +
  # geom_point(data=foo2, aes(x=factor(r), y=alphVal), 
  #            shape=17, color="white") +
  facet_grid(type_net ~ modName ~ alph_type) +
  labs(x="Assortativity", y=expression(alpha), 
       fill="Mean \nPrevalence \nRatio", title="R0=3.5") +
  theme_light() +
  theme(axis.text=element_text(size=hs),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=hs,face="bold"),
        legend.title = element_text(size=hs),
        legend.text = element_text(size=hs), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 18, color="Black")) 

```

Take-aways for male-bias: 

* Low transmissibility
* With endemic (SLIRS) dynamics
* Infectious period especially, and also susceptibility can lead to male bias
* Interaction between sex-traits and assortativity on male-bias 

\newpage

```{r outbreak-compare1, fig.cap="Effects of network structure on epidemic size in SLIR model. Hortizontal panels show different network types (scale-free and small-world). "}

foo <- res %>% 
  filter(modName%in% c("SIR", "SLIR"), alph_val==1) %>%
  group_by(modName, tau, r, type_net) %>%
  summarise(out_size=mean(recovered_prev))

foo %>%
  filter(modName=="SLIR") %>%
  ggplot(aes(x=as.factor(r), y=factor(tau))) +
  geom_tile(aes(fill=out_size)) + 
  scale_fill_viridis_c() +
  facet_grid(type_net ~ .) +
  labs(x="Assortativity", y=expression(tau), 
       fill="Epidemic size", title = "SLIR") +
  theme_light() +
  theme(axis.text=element_text(size=14),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=18,face="bold"),
        legend.title = element_text(size=18),
        legend.text = element_text(size=18), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 18, color="Black"))

```

```{r outbreak-compare2, fig.cap="Effects of network structure on endemic prevalence in SLIRS model. Hortizontal panels show different network types (scale-free and small-world). "}

foo <- res %>% 
  filter(modName%in% c("SIRS", "SLIRS"), alph_val==1) %>%
  group_by(modName, tau, r, type_net) %>%
  summarise(prev=mean(infected_prev))

foo %>%
  filter(modName=="SLIRS") %>%
  ggplot(aes(x=as.factor(r), y=factor(tau))) +
  geom_tile(aes(fill=prev)) + 
  scale_fill_viridis_c() +
  facet_grid(type_net ~ .) +
  labs(x="Assortativity", y=expression(tau), 
       fill="Endemic prevalence", title = "SLIRS") +
  theme_light() +
  theme(axis.text=element_text(size=14),
        axis.text.x = element_text(hjust=1, angle=45),
        axis.title=element_text(size=18,face="bold"),
        legend.title = element_text(size=18),
        legend.text = element_text(size=18), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        strip.text = element_text(size = 18, color="Black"))

```

